branch-defaults:
  default:
    environment: kfdev
  master:
    environment: kfdev
environment-defaults:
  kfdev:
    branch: null
    repository: null
global:
  application_name: kfdev
  default_ec2_keyname: null
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
